### ISSUE TITLE
Euler estimator

### ISSUE THREAD

**Issue by RavenHex1296** [snowthesprite/simulation#4]
If you want to make your Euler estimator code just a bit shorter, you could always take away the color code. You don't need to give them set values. As long as you put the plotting part in a for loop, it'll set them to different colors. You won't need the other complex code to make sure they are all random colors that aren't the same.

**Comment by snowthesprite** [comment]
Yeah, I didn't know it would do that when I wrote it, so I put in a color function so not everything would "be the same color". Its gone now
